"""empty message

Revision ID: dfb35452d458
Revises: 5e2c32e8ed30
Create Date: 2023-01-16 16:24:15.511099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb35452d458'
down_revision = '5e2c32e8ed30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('tarbijahinnaindeks', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('index_value',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('change_to_previous_month',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('change_to_previous_month_in_percent',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('previous_close',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarbijahinnaindeks', schema=None) as batch_op:
        batch_op.create_unique_constraint('index_unique', ['year', 'month'])
        batch_op.alter_column('previous_close',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('change_to_previous_month_in_percent',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('change_to_previous_month',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('index_value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('order_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
